### ISSUE TITLE
Properly implement `java/lang/IllegalArgumentException`

### ISSUE THREAD

**Issue by tilastokeskus** [DenisCarriere/turf-jsts#1]
[src/java/lang/IllegalArgumentException.js](https://github.com/DenisCarriere/turf-jsts/blob/master/src/java/lang/IllegalArgumentException.js) is not properly implemented, and this threw me off while using the `@turf/intersect` package badly 😉

**Comment by tilastokeskus** [comment]
Submitted a PR: https://github.com/DenisCarriere/turf-jsts/pull/2

**Comment by DenisCarriere** [comment]
👍 Thanks, I'll patch both `turf-jsts` & `@turf/intersect`, this change won't be reflected in the main `@turf/turf` repo just yet until the next minor release.
