### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by Freddixx** [DenisCarriere/turf-jsts#7]
Hi,

first of all thanks for that great library! It has really helped us a lot so far! 🙂 

## Problem
Our license checker is warning us about this sub package. Without it we would not be able to roll out our code.

## Suggestion
Could you add or link a valid license to this package?

Let me know if I can help!

Cheers,
Fred

**Comment by DenisCarriere** [comment]
This library shouldn't be used in any dependencies

If it does, it should use the native `jsts` library

https://github.com/bjornharrtell/jsts

**Comment by Freddixx** [comment]
I see. I know that the package is referenced by turf-js and hence marked as not having a license:

![image](https://user-images.githubusercontent.com/1607909/63162724-97856180-c023-11e9-8cf8-72ebacd60be0.png)

I ran `yarn why` on it and this was the output:

```
yarn why v1.12.3
[1/4] 🤔  Why do we have the module "turf-jsts"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "turf-jsts@1.2.3"
info Reasons this module exists
   - "@turf#turf#@turf#union" depends on it
   - Hoisted from "@turf#turf#@turf#union#turf-jsts"
   - Hoisted from "@turf#turf#@turf#difference#turf-jsts"
   - Hoisted from "@turf#turf#@turf#intersect#turf-jsts"
   - Hoisted from "@turf#turf#@turf#buffer#turf-jsts"
info Disk size without dependencies: "4.06MB"
info Disk size with unique dependencies: "4.06MB"
info Disk size with transitive dependencies: "4.06MB"
info Number of shared dependencies: 0
✨  Done in 0.89s.
```

Any thoughts?

**Comment by Freddixx** [comment]
@DenisCarriere Any news here?

**Comment by jruddell** [comment]
@DenisCarriere I also have the same issue, using WhiteSource to look for license compliance. `turf-js` has this [listed as a dependency](https://github.com/Turfjs/turf/blob/17002ccd57e04e84ddb38d7e3ac8ede35b019c58/packages/turf-buffer/package.json#L61), and [is definitely using it](https://github.com/Turfjs/turf/blob/17002ccd57e04e84ddb38d7e3ac8ede35b019c58/packages/turf-buffer/index.js). Is it fine to open source this library?

**Comment by Freddixx** [comment]
@jruddell Good to see there is at least somebody else. I already started doubting myself 😄 

@DenisCarriere Would you mind providing a license?

**Comment by donocode** [comment]
Hey @DenisCarriere, I have also encountered this issue, without a permissive license in this package legally no one is able to take a dependency on any package that has this package as a dependency (in our case `@nebula.gl/layers` -> `@turf/buffer` -> `turf-jsts`). 

So would you be able to add a license? Preferably just the same as [turf](https://github.com/Turfjs/turf/blob/master/packages/turf-buffer/LICENSE)

**Comment by donocode** [comment]
Actually I found the license `(EDL-1.0 OR EPL-1.0)` specified in `package.json`, presumably copied from `jsts` but it doesn't seem like you are able to specify that one. I'll try to get approval to use it based on that, but you should probably include a LICENSE file for EDL-1.0 to make it easier for others

**Comment by priyaaank** [comment]
Still waiting for a license file to be included here
